# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-30 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infrastructure_name', models.CharField(max_length=20)),
                ('infrastructure_pubsub', models.PositiveIntegerField()),
                ('infrastructure_nacl', models.PositiveIntegerField()),
                ('infrastructure_sg', models.PositiveIntegerField()),
                ('infrastructure_pubinst', models.PositiveIntegerField()),
                ('infrastructure_owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infrastructure_name', models.CharField(max_length=20)),
                ('infrastructure_creation_date', models.DateTimeField(auto_now_add=True)),
                ('infrastructure_owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ami_type', models.CharField(choices=[('Amazon AMI', 'Amazon Linux AMI 2018.03.0'), ('RedHat', 'Red Hat Entreprise Linux 7.5'), ('Ubuntu Server', 'Ubuntu Server 16.04 LTS')], default='T2.micro', max_length=20)),
                ('instance_type', models.CharField(choices=[('.micro', 'T2.micro'), ('small', 'T2.small'), ('tiny', 'T2.tiny')], default='Amazon Linux AMI 2018.03.0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NACL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacl_name', models.CharField(max_length=20)),
                ('nacl_src_ip', models.GenericIPAddressField()),
                ('nacl_in_prot', models.CharField(max_length=20)),
                ('nacl_out_prot', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_name', models.CharField(max_length=20)),
                ('sg_src_ip', models.GenericIPAddressField()),
                ('sg_in_prot', models.CharField(max_length=20)),
                ('sg_out_prot', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
