# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-30 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customstack',
            name='infrastructure_pubsub',
        ),
    ]
