# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-30 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_remove_customstack_infrastructure_pubsub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nacl',
            name='nacl_src_ip',
        ),
        migrations.RemoveField(
            model_name='sg',
            name='sg_src_ip',
        ),
    ]
