# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-01 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20181031_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='inst_infra',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nacl',
            name='nacl_infra',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sg',
            name='sg_infra',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='instance',
            name='instance_type',
            field=models.CharField(choices=[('t2.micro', 't2.micro')], default='Amazon Linux AMI 2018.03.0', max_length=20),
        ),
    ]
