# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-03 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_nacl2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ami_type', models.CharField(choices=[('Amazon AMI', 'Amazon Linux AMI 2018.03.0'), ('RedHat', 'Red Hat Entreprise Linux 7.5'), ('Ubuntu Server', 'Ubuntu Server 16.04 LTS')], default='T2.micro', max_length=20)),
                ('instance_type', models.CharField(choices=[('t2.micro', 't2.micro')], default='Amazon Linux AMI 2018.03.0', max_length=20)),
                ('ami_type2', models.CharField(choices=[('Amazon AMI', 'Amazon Linux AMI 2018.03.0'), ('RedHat', 'Red Hat Entreprise Linux 7.5'), ('Ubuntu Server', 'Ubuntu Server 16.04 LTS')], default='T2.micro', max_length=20)),
                ('instance_type2', models.CharField(choices=[('t2.micro', 't2.micro')], default='Amazon Linux AMI 2018.03.0', max_length=20)),
                ('ami_type3', models.CharField(choices=[('Amazon AMI', 'Amazon Linux AMI 2018.03.0'), ('RedHat', 'Red Hat Entreprise Linux 7.5'), ('Ubuntu Server', 'Ubuntu Server 16.04 LTS')], default='T2.micro', max_length=20)),
                ('instance_type3', models.CharField(choices=[('t2.micro', 't2.micro')], default='Amazon Linux AMI 2018.03.0', max_length=20)),
                ('inst_infra', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
