# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-03 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0012_nacl3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ami_type', models.CharField(choices=[('Amazon AMI', 'Amazon Linux AMI 2018.03.0'), ('RedHat', 'Red Hat Entreprise Linux 7.5'), ('Ubuntu Server', 'Ubuntu Server 16.04 LTS')], default='T2.micro', max_length=20)),
                ('instance_type', models.CharField(choices=[('t2.micro', 't2.micro')], default='Amazon Linux AMI 2018.03.0', max_length=20)),
                ('ami_type2', models.CharField(choices=[('Amazon AMI', 'Amazon Linux AMI 2018.03.0'), ('RedHat', 'Red Hat Entreprise Linux 7.5'), ('Ubuntu Server', 'Ubuntu Server 16.04 LTS')], default='T2.micro', max_length=20)),
                ('instance_type2', models.CharField(choices=[('t2.micro', 't2.micro')], default='Amazon Linux AMI 2018.03.0', max_length=20)),
                ('ami_type3', models.CharField(choices=[('Amazon AMI', 'Amazon Linux AMI 2018.03.0'), ('RedHat', 'Red Hat Entreprise Linux 7.5'), ('Ubuntu Server', 'Ubuntu Server 16.04 LTS')], default='T2.micro', max_length=20)),
                ('instance_type3', models.CharField(choices=[('t2.micro', 't2.micro')], default='Amazon Linux AMI 2018.03.0', max_length=20)),
                ('ami_type4', models.CharField(choices=[('Amazon AMI', 'Amazon Linux AMI 2018.03.0'), ('RedHat', 'Red Hat Entreprise Linux 7.5'), ('Ubuntu Server', 'Ubuntu Server 16.04 LTS')], default='T2.micro', max_length=20)),
                ('instance_type4', models.CharField(choices=[('t2.micro', 't2.micro')], default='Amazon Linux AMI 2018.03.0', max_length=20)),
                ('inst_infra', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NACL4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacl_name', models.CharField(max_length=20)),
                ('nacl_in_prot', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('nacl_out_prot', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('nacl_in_prot2', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('nacl_out_prot2', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('nacl_in_prot3', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('nacl_out_prot3', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('nacl_in_prot4', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('nacl_out_prot4', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('nacl_infra', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SG4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_name', models.CharField(max_length=20)),
                ('sg_in_prot', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('sg_out_prot', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('sg_in_prot2', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('sg_out_prot2', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('sg_in_prot3', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('sg_out_prot3', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('sg_in_prot4', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('sg_out_prot4', models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20)),
                ('sg_infra', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='nacl',
            name='nacl_in_prot',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='nacl2',
            name='nacl_in_prot',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='nacl2',
            name='nacl_in_prot2',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='nacl3',
            name='nacl_in_prot',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='nacl3',
            name='nacl_in_prot2',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='nacl3',
            name='nacl_in_prot3',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sg',
            name='sg_in_prot',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sg',
            name='sg_out_prot',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sg2',
            name='sg_in_prot',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sg2',
            name='sg_in_prot2',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sg2',
            name='sg_out_prot',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sg2',
            name='sg_out_prot2',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sg3',
            name='sg_in_prot',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sg3',
            name='sg_in_prot2',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sg3',
            name='sg_in_prot3',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sg3',
            name='sg_out_prot',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sg3',
            name='sg_out_prot2',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sg3',
            name='sg_out_prot3',
            field=models.CharField(choices=[('SSH', 'SSH'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
    ]
