# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-05 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0014_auto_20181105_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='inst_owner',
        ),
        migrations.RemoveField(
            model_name='instance2',
            name='inst_owner',
        ),
        migrations.RemoveField(
            model_name='instance3',
            name='inst_owner',
        ),
        migrations.RemoveField(
            model_name='instance4',
            name='inst_owner',
        ),
        migrations.RemoveField(
            model_name='nacl',
            name='nacl_owner',
        ),
        migrations.RemoveField(
            model_name='nacl2',
            name='nacl_owner',
        ),
        migrations.RemoveField(
            model_name='nacl3',
            name='nacl_owner',
        ),
        migrations.RemoveField(
            model_name='nacl4',
            name='nacl_owner',
        ),
        migrations.RemoveField(
            model_name='sg',
            name='sg_owner',
        ),
        migrations.RemoveField(
            model_name='sg2',
            name='sg_owner',
        ),
        migrations.RemoveField(
            model_name='sg3',
            name='sg_owner',
        ),
        migrations.RemoveField(
            model_name='sg4',
            name='sg_owner',
        ),
    ]
